apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: txeip99or-python
  janus-idp.io/tekton: txeip99or-python
  backstage.io/kubernetes-id: txeip99or-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: txeip99or-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
